apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-uufl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-uufl
    app.kubernetes.io/part-of: test-app-jner
  name: test-component-uufl
  namespace: build-e2e-hacbs-htdh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-uufl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-uufl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:9f9c7f1481fa6914e84342c58f56ad22edcc8adc9867509e3a0a49685e2c4277
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
